name: Test

on:
  push:
    branches:
      # Push will only build on branches that match this name
      # Pull requests will override this, so pushes to pull requests will still build
      - main
  pull_request:
    branches:
      - main

jobs:

  test-coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9.x"

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Generate coverage report
      run: |
        uv run pytest --cov=changelog_gen --cov-report=xml --cov-config=pyproject.toml -vvv

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: NRWLDev/changelog-gen
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        yml: ./codecov.yml
        fail_ci_if_error: false

  test-python-versions:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: ["3.9.x", "3.10.x", "3.11.x", "3.12.x"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v2

    - name: Install dependencies
      run: uv sync --all-extras

    - name: Test with pytest
      run: |
        uv run pytest
